jdk:
- openjdk8

dist: trusty

android:
  components:
    - android-29
    - build-tools-29.0.2

script:
- git clone --depth=1 --branch=master https://github.com/Anuken/Arc ../Arc
- git clone --depth=1 --branch=master https://github.com/Anuken/Mindustry ../Mindustry
- cd Mindustry
- "./gradlew desktop:dist -Pbuildversion=${TRAVIS_BUILD_NUMBER}"
- "./gradlew server:dist -Pbuildversion=${TRAVIS_BUILD_NUMBER}"
- "./gradlew android:assembleDebug -Pbuildversion=${TRAVIS_BUILD_NUMBER}"


deploy:
  - provider: releases
    skip_cleanup: true
    draft: false
    file:
    - desktop/build/libs/Mindustry.jar
    - server/build/libs/server-release.jar
    - android/build/libs/android-release.apk
    on:
      repo: Anuken/Mindustry
      tags: true
